version: '3'
services:
  napcat:
    environment:
        - ACCOUNT=123456789
    ports:
        - "3001:3001"
        - "6099:6099"
    container_name: napcat
    networks: 
      - qqbot
    restart: always
    image: mlikiowa/napcat-docker:latest
  driver:
    image: yoaken/my-qqbot:u215
    container_name: my-qqbot
    restart: always
    networks: 
      - qqbot
    volumes:
      - ./config.yaml:/app/config.yaml
      - data/:/app/data
networks:
  qqbot:
    driver: bridge
